---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/14 16:40
---

ConstEnum = {}

ConstEnum.modName = "ksptooi-server-commons-preprocess"
ConstEnum.version = "1.4-G"
ConstEnum.ctx = "KspTooi"