---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/14 16:40
---

local constEnum = {}

constEnum.modName = "ksptooi-server-commons-preprocess"
constEnum.version = "1.4-G"
constEnum.ctx = "KspTooi"