---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/14 16:40
---

ConstEnum = {}

ConstEnum.modName = "SpaceExplorationExtendsPack"
ConstEnum.modName1 = "SpaceExplorationExtendsPack UU-Industrial"
ConstEnum.modName2 = "UU-Industrial"

ConstEnum.formerName = "KspTooi-Server-Common-Preprocess"
ConstEnum.modPrefix = "kscp"



ConstEnum.version = "1.4-K"
ConstEnum.ctx = "KspTooi"

ConstEnum.kw = "kW"
ConstEnum.mw = "mW"
ConstEnum.w = "w"


ConstEnum.collisionMaskAllowInSpace = {"object-layer", "train-layer", "floor-layer","water-tile"}

ConstEnum.collisionMaskAllowInGround = {"water-tile","object-layer", "train-layer", "floor-layer",space_collision_layer}

ConstEnum.collisionMaskAllowInGroundAndSpace = {"object-layer", "train-layer", "floor-layer","water-tile"}


ConstEnum.collisionMaskAllowInWater = {"object-layer", "train-layer", "floor-layer"}