---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/24 23:35
---

FluidEnum = {}

FluidEnum.crudeOil="crude-oil"
FluidEnum.fluidUnknown="fluid-unknown"
FluidEnum.heavyOil="heavy-oil"
FluidEnum.lightOil="light-oil"
FluidEnum.lubricant="lubricant"
FluidEnum.petroleumGas="petroleum-gas"
FluidEnum.steam="steam"
FluidEnum.sulfuricAcid="sulfuric-acid"
FluidEnum.water="water"
