---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/4 10:11
---

msk_ground_only = {
    {"water-tile","object-layer", "train-layer", "floor-layer",space_collision_layer}
}


msk_allow_space = {
    {"water-tile","object-layer", "train-layer", "floor-layer"}
}


msk_space_only = {
    {"water-tile","object-layer", "train-layer", "floor-layer"}
}