---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/25 21:21
---

RecipeCategoryEnum = {}

RecipeCategoryEnum.advancedCrafting="advanced-crafting"
RecipeCategoryEnum.basicCrafting="basic-crafting"
RecipeCategoryEnum.centrifuging="centrifuging"
RecipeCategoryEnum.chemistry="chemistry"
RecipeCategoryEnum.crafting="crafting"
RecipeCategoryEnum.craftingWithFluid="crafting-with-fluid"
RecipeCategoryEnum.oilProcessing="oil-processing"
RecipeCategoryEnum.rocketBuilding="rocket-building"
RecipeCategoryEnum.smelting="smelting"
