---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 3:01
---

ToolEnum = {}

ToolEnum.automationSciencePack="automation-science-pack"
ToolEnum.chemicalSciencePack="chemical-science-pack"
ToolEnum.logisticSciencePack="logistic-science-pack"
ToolEnum.militarySciencePack="military-science-pack"
ToolEnum.productionSciencePack="production-science-pack"
ToolEnum.spaceSciencePack="space-science-pack"
ToolEnum.utilitySciencePack="utility-science-pack"