---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/14 17:33
---

TypeEnum = {}

TypeEnum.item = "item"
TypeEnum.recipe = "recipe"
TypeEnum.entity = "entity"
TypeEnum.technology = "technology"

TypeEnum.assemblingMachine = "assembling-machine"
TypeEnum.miningDrill = "mining-drill"