---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/11 17:59
---

data.raw["solar-panel"]["se-space-solar-panel"].production = "240kW" --origin 400kw
data.raw["solar-panel"]["se-space-solar-panel-2"].production = "480kW" --origin 800kw
data.raw["solar-panel"]["se-space-solar-panel-3"].production = "960kW" --origin 1600kw