---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/28 22:23
---

local itemStack = 100

--需要统一堆叠的物品名称
local item = {
    "rocket-fuel"
}


for i,itemName in pairs(item) do

    local dataItem = data.raw["item"][itemName]

    if dataItem~=nil then
        dataItem.stack_size = itemStack
    end

end



