---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/2/12 21:30
---


aspectService.get(TypeEnum.item,ItemEnum.laserTurret)
        :setName(db.forName("prism-tower"))
        :setItemPlaceResult(db.forName("prism-tower"))
        :setItemIcon(db.forRes("PrismTower/res/hr-genric-object-gen3-prism-tower-icon.png"))
        :setItemIconSize(128)
        :insertInto()