---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/4 17:45
---

data.raw["recipe"]["underground-pipe-segment-space"].ingredients = {
    {"underground-pipe-segment-t1", 1},
    {"copper-cable", 2 },
    {"plastic-bar", 1 },
    {"glass", 1 },
}

data.raw["recipe"]["space-pipe-coupler"].ingredients =
{
    {'small-pipe-coupler', 1},
    {"copper-cable", 2 },
    {"plastic-bar", 1 },
}

data.raw["technology"]["advanced-underground-piping-space"].prerequisites = {'advanced-underground-piping-t3'}

data.raw["technology"]["advanced-underground-piping-space"].unit = {
    count = 200,
    ingredients = {
        {'automation-science-pack', 1},
        {'logistic-science-pack', 1},
        {'chemical-science-pack', 1},
    },
    time = 30
}
