---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 21:27
---

aspectService.create(TypeEnum.recipeCategory,db.forName("uu-fabricator-category")):insertInto()


aspectService.get(TypeEnum.furnace,ItemEnum.electricFurnace)
        :setName(ConstEnum.modPrefix.."uu-matter-fabricator")
        :setEntityCollisionMask(ConstEnum.collisionMaskAllowInGroundAndSpace)
        :setAllowInSpace(true)
        :setEntityMaxHealth(1500)
        :setEntityCraftSpeed(4)
        :setFurnaceWorkingVisualisations(nil)
        :setEntityModuleSpecification({
            module_slots = 4
        })

        :setEntityCraftingCategories({db.forName("uu-fabricator-category")})

        :setEntityCollisionBox({{-2.9, -2.9}, {2.9, 2.9}})  --左右 上下
        :setEntitySelectionBox({{-3.2, -3.2}, {3.2, 3.2}})
        :setEntityDrawingBox({{-3, -3}, {3, 3}})
        :setEntityAnimation({

            layers ={

                {
                    filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-uu.png",
                    priority = "high",
--[[                    width = 978,
                    height = 895,]]
                    width = 512,
                    height = 512,
                    frame_count = 32,
                    line_length = 8,
                    shift = util.by_pixel(0, 0),
                    scale = 0.52,
                    hr_version =
                    {
                        filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-uu.png",
                        priority = "high",
                        width = 512,
                        height = 512,
                        frame_count = 32,
                        line_length = 8,
                        shift = util.by_pixel(0, 0),
                        scale = 0.52
                    }
                },
                {
                    filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-gen1-shadow.png",
                    priority = "high",
                    width = 512,
                    height = 512,
                    frame_count = 32,
                    line_length = 8,
                    draw_as_shadow = true,
                    shift = util.by_pixel(0, 0),
                    scale = 0.52,
                    hr_version =
                    {
                        filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-gen1-shadow.png",
                        priority = "high",
                        width = 512,
                        height = 512,
                        frame_count = 32,
                        line_length = 8,
                        draw_as_shadow = true,
                        shift = util.by_pixel(0, 0),
                        scale = 0.52
                    }
                }

            }

        }):joinToData()