---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 21:27
---


aspectService.getItem(ItemEnum.electricFurnace)
        :setName(ConstEnum.modPrefix.."uu-matter-fabricator")
        :setItemPlaceResult(ConstEnum.modPrefix.."uu-matter-fabricator")
        :setItemStackSize(10)
        :setItemIcon(ConstEnum.modulesPath.."/UUMatterFabricator/res/hr-genric-object-gen3-uu-fabricator-icon.png")
        :setItemIconSize(128)
        :joinToData()