---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 21:27
---

local effects = {
    {
        type = "unlock-recipe",
        recipe = db.forName("uu-matter-fabricator")
    },
    {
        type = "unlock-recipe",
        recipe = db.forName("uu-duplicator")
    }
}


aspectConverter.toTechnology(aspectService.create(TypeEnum.technology))
               :setName(db.forName("uu-matter-fabricator"))
               :setIcon(ConstEnum.modulesPath.."/UUMatterFabricator/res/hr-genric-object-gen3-uu-fabricator-icon.png")
               :setIconSize(128)
               :setPrerequisites({db.forName("prism-structure")})
               :setOrder("u[uu-matter-fabricator]")
               :setUnit({
    count = 600,
    ingredients = {
        {ToolEnum.automationSciencePack, 1},
        {ToolEnum.logisticSciencePack, 1},
        {ToolEnum.chemicalSciencePack, 1},
    },
    time = 30
})
               :setEffects(effects)
               :insertInto()