---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/28 21:52
---

local function get_recipes_for_barrel(name)
    local recipes = data.raw["recipe"]
    if recipes then
        return recipes["fill-" .. name], recipes["empty-" .. name]
    end
    return nil
end


for name, fluid in pairs(data.raw["fluid"]) do

    local barrel_name = fluid.name .. "-barrel"

    local recipe_fill,recipe_empty = get_recipes_for_barrel(barrel_name);

    if recipe_fill~=nil and recipe_empty~=nil then

        data.raw["recipe"]["fill-"..barrel_name].ingredients ={
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        }

        data.raw["recipe"]["empty-"..barrel_name].results={
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        }

    end

end



