---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/26 16:02
---

local deliveryCapsule_steel_exp = table.deepcopy(data.raw["recipe"]["se-delivery-cannon-capsule"])
local deliveryCapsule_stell = table.deepcopy(data.raw["recipe"]["se-delivery-cannon-capsule"])

local delivertTechnology = table.deepcopy(data.raw["technology"]["se-delivery-cannon"])


deliveryCapsule_stell.name = "kscp-delivery-cannon-capsule-steel"
deliveryCapsule_stell.ingredients = {
    { "steel-plate", 10 }
}

deliveryCapsule_steel_exp.name = "kscp-delivery-cannon-capsule-steel-exp"
deliveryCapsule_steel_exp.ingredients = {
    { "steel-plate", 4 },
    { "explosives", 2 },
}

data:extend({deliveryCapsule_steel_exp,deliveryCapsule_stell})


table.insert(delivertTechnology.effects,{ type = "unlock-recipe", recipe = "kscp-delivery-cannon-capsule-steel", })
table.insert(delivertTechnology.effects,{ type = "unlock-recipe", recipe = "kscp-delivery-cannon-capsule-steel-exp", })



data:extend({delivertTechnology})


