---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/26 15:42
---


data.raw["recipe"]["warehouse-basic"].ingredients =
{
    { "steel-plate", 8000 },
    { "stone-brick", 4000 },
    { "iron-stick", 10000 },
    { "concrete", 10000},
}


data.raw["recipe"]["storehouse-basic"].ingredients =
{
    { "steel-plate", 4000 },
    { "stone-brick", 2000 },
    { "iron-stick", 5000 },
    { "concrete", 5000},
}