---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/26 10:48
---
local aspectObject = require("aspect.AspectObject")
local aspectRecipe = require("aspect.AspectRecipe")
local aspectEntity = require("aspect.AspectEntity")
local aspectTechnology = require("aspect.AspectTechnology")
local aspectAssemblingMachine = require("aspect.AspectAssemblingMachine")
local aspectFurnace = require("aspect.AspectFurnace")
local aspectItem = require("aspect.AspectItem")


local aspectConverter = {}

---@return aspectObject
function aspectConverter.toObject(input)
    return aspectObject:import(input)
end

---@return aspectRecipe
function aspectConverter.toRecipe(input)
    return aspectRecipe:import(input)
end

---@return aspectEntity
function aspectConverter.toEntity(input)
    return aspectEntity:import(input)
end

---@return aspectTechnology
function aspectConverter.toTechnology(input)
    return aspectTechnology:import(input)
end

---@return aspectAssemblingMachine
function aspectConverter.toAssemblingMachine(input)
    return aspectAssemblingMachine:import(input)
end

---@return aspectFurnace
function aspectConverter.toFurnace(input)
    return aspectFurnace:import(input)
end

---@return aspectItem
function aspectConverter.toItem(input)
    return aspectItem:import(input)
end

return aspectConverter