---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/25 15:31
---
---
local aspectIngredients = require("aspect.AspectIngredients")

local db = {}


function db.forName(name)
    return ConstEnum.modPrefix..name
end

function db.forRes(resPath)
    return ConstEnum.modulesPath..resPath
end


function db.buildColor(r,g,b,a)
    return {r=r,g=g,b=b,a=a}
end

function db.buildEnergyAsW(energy)
    return energy..ConstEnum.w
end

function db.buildEnergyAsKW(energy)
    return energy..ConstEnum.kw
end

function db.buildEnergyAsMW(energy)
    return energy..ConstEnum.mw
end

function db.buildIngredients(type,name,amount,catalystAmount)

    aspectIngredients.create({})

    if catalystAmount==nil then
        aspectIngredients:insert(type,name,amount)
        return aspectIngredients
    end

    aspectIngredients:insert(type,name,amount)
    return aspectIngredients
end


function db.forInnerModules(modules)
    return ConstEnum.modulesPath..modules
end

function db.forSupportModules(modules)
    return ConstEnum.supportModulesPath..modules
end


return db
