---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/25 15:31
---

local db = {}


function db.forName(name)
    return ConstEnum.modPrefix..name
end

function db.forRes(resPath)
    return ConstEnum.modulesPath..resPath
end
