---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/18 22:48
---



aspectService.get(TypeEnum.assemblingMachine,"se-core-miner"):removeFromData()
aspectService.get(TypeEnum.miningDrill,"se-core-miner-drill"):removeFromData()

aspectService.getItem("se-core-miner"):removeFromData()
aspectService.getRecipe("se-core-miner"):removeFromData()

aspectService.getTechnology("se-core-miner"):setTechnologyEffects(nil):insertToData()