---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/4 17:22


local base = data.raw["item"]["se-liquid-rocket-fuel-barrel"]


if base~=nil then

data:extend({
    {
        type = "item",
        name = "se-delivery-cannon-package-".."se-liquid-rocket-fuel-barrel",
        icon = "__space-exploration-graphics__/graphics/icons/delivery-cannon-capsule.png",
        icon_size = 64,
        order = order,
        flags = {"hidden"},
        subgroup = base.subgroup or "delivery-cannon-capsules",
        stack_size = 1,
        localised_name = {"item-name.se-delivery-cannon-capsule-packed", base.localised_name or {type.."-name."..resource.name}}
    },
    {
        type = "recipe",
        name = "se-delivery-cannon-pack-" .. "se-liquid-rocket-fuel-barrel",
        icon = base.icon,
        icon_size = base.icon_size,
        icon_mipmaps = base.icon_mipmaps,
        icons = base.icons,
        result = "se-delivery-cannon-package-".."se-liquid-rocket-fuel-barrel",
        enabled = true,
        energy_required = 5,
        ingredients = {
            { "se-delivery-cannon-capsule", 1 },
            { type = "item", name = "se-liquid-rocket-fuel-barrel", amount = 75},
        },
        requester_paste_multiplier = 1,
        always_show_made_in = false,
        category = "delivery-cannon",
        hide_from_player_crafting = true,
        hide_from_stats = true,
        localised_name = {"item-name.se-delivery-cannon-capsule-packed", base.localised_name or {type.."-name."..resource.name}},
        allow_decomposition = false
    },
})

end

