---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 14:45
---
local compactReactor =  {

    type = "burner-generator",
    name = "kscp-compact-nuclear-reactor",
    icon = "__base__/graphics/icons/nuclear-reactor.png",
    icon_size = 64, icon_mipmaps = 4,
    flags = {"placeable-neutral","player-creation"},
    minable = {mining_time = 5, result = "kscp-compact-nuclear-reactor"},
    max_health = 5000,
    corpse = "nuclear-reactor-remnants",
    dying_explosion = "nuclear-reactor-explosion",

    effectivity = 0.375,
    collision_box = {{-2.2, -2.2}, {2.2, 2.2}},
    selection_box = {{-2.5, -2.5}, {2.5, 2.5}},

    energy_source = {
        type = "electric",
        usage_priority = "secondary-output"
    },

    burner = {
        type = "burner",
        fuel_category = "nuclear",
        effectivity = 1,
        fuel_inventory_size = 2,
        burnt_inventory_size = 1,
        light_flicker =
        {
            color = {0,0,0},
            minimum_intensity = 0.7,
            maximum_intensity = 0.95
        }
    },

    animation = {
        layers =
        {
            {
                filename = "__base__/graphics/entity/nuclear-reactor/reactor.png",
                width = 154,
                height = 158,
                shift = util.by_pixel(-6, -6),
                hr_version =
                {
                    filename = "__base__/graphics/entity/nuclear-reactor/hr-reactor.png",
                    width = 302,
                    height = 318,
                    scale = 0.5,
                    shift = util.by_pixel(-5, -7)
                }
            },
            {
                filename = "__base__/graphics/entity/nuclear-reactor/reactor-shadow.png",
                width = 263,
                height = 162,
                shift = { 1.625 , 0 },
                draw_as_shadow = true,
                hr_version =
                {
                    filename = "__base__/graphics/entity/nuclear-reactor/hr-reactor-shadow.png",
                    width = 525,
                    height = 323,
                    scale = 0.5,
                    shift = { 1.625, 0 },
                    draw_as_shadow = true
                }
            }
        }
    },

    working_sound =
    {
        sound =
        {
            {
                filename = "__base__/sound/nuclear-reactor-1.ogg",
                volume = 0.55
            },
            {
                filename = "__base__/sound/nuclear-reactor-2.ogg",
                volume = 0.55
            }
        },
        --idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.3 },
        max_sounds_per_type = 3,
        fade_in_ticks = 4,
        fade_out_ticks = 20
    },

    min_perceived_performance = 0.25,
    performance_to_sound_speedup = 0.5,
    max_power_output = "20MW",
}

data:extend({compactReactor})