---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 14:45
---


local compactReactorRecipe = table.deepcopy(data.raw["recipe"]["nuclear-reactor"])

compactReactorRecipe.result = "kscp-compact-nuclear-reactor"

compactReactorRecipe.ingredients = {
    {"concrete", 500},
    {"steel-plate", 500},
    {"advanced-circuit", 500},
    {"copper-plate", 500},
    {"heat-exchanger", 15},
    {"steam-turbine", 8}
}

data:extend({compactReactorRecipe})

