---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/18 17:40
---
local aspectService = require("modules.aspectcommonservices.AspectService")


for name,fluid in pairs(data.raw["fluid"]) do

    local barrelName = fluid.name + "-barrel"

    local recipeFill = aspectService.getRecipe("fill-"..fluid.name.."-barrel")
    local recipeEmpty = aspectService.getRecipe("empty-"..fluid.name.."-barrel")


    if recipeFill:isNotEmpty() and recipeEmpty:isNotEmpty() then

        recipeFill:setRecipeIngredients({
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        })

        recipeEmpty:setRecipeResults({
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        })

        recipeFill:update()
        recipeEmpty:update()

    end



end