---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 14:45
---

--紧凑型核反应堆
local compactReactor = {
    type = "item",
    name = "kscp-compact-nuclear-reactor",
    icon = "__base__/graphics/icons/nuclear-reactor.png",
    icon_size = 64, icon_mipmaps = 4,
    subgroup = "energy",
    order = "f[nuclear-energy]-a[reactor]",
    place_result = "kscp-compact-nuclear-reactor",
    stack_size = 10
}

data:extend({compactReactor})