---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 14:45
---



local compactReactorRecipe = {
    type = "recipe",
    name = "kscp-compact-nuclear-reactor",
    energy_required = 8,
    enabled = false,
    ingredients = {
        {"concrete", 500},
        {"steel-plate", 500},
        {"advanced-circuit", 500},
        {"copper-plate", 500},
        {"heat-exchanger", 10},
        {"steam-turbine", 8}
    },
    result = "kscp-compact-nuclear-reactor",
    requester_paste_multiplier = 1
}

data:extend({compactReactorRecipe})
