---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 14:45
---

--[[table.insert(data.raw["technology"]["nuclear-power"].effects,{

    type = "unlock-recipe",
    recipe = "kscp-compact-nuclear-reactor"

})]]

local compactReactorTechnology = {
    type = "technology",
    name = "compact-nuclear-power",
    icon_size = 256, icon_mipmaps = 4,
    icon = "__base__/graphics/technology/nuclear-power.png",
    effects =
    {
        {
            type = "unlock-recipe",
            recipe = "kscp-compact-nuclear-reactor"
        }
    },
    prerequisites = {"nuclear-power"},
    unit =
    {
        ingredients =
        {
            {"automation-science-pack", 1},
            {"logistic-science-pack", 1},
            {"chemical-science-pack", 1}
        },
        time = 30,
        count = 500
    },
    order = "e-p-b-c"
}

data:extend({compactReactorTechnology})