---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 21:27
---

aspectService.create(TypeEnum.recipeCategory,db.forName("ore-crusher-category")):insertInto()


aspectService.get(TypeEnum.furnace,ItemEnum.electricFurnace)
        :setName(db.forName("ore-crusher"))
        :setEntityCollisionMask(ConstEnum.collisionMaskAllowInGroundAndSpace)
        :setAllowInSpace(true)
        :setEntityMaxHealth(1500)
        :setEntityCraftSpeed(5)
        :setFurnaceWorkingVisualisations(nil)
        :setEntityModuleSpecification({
            module_slots = 4
        })

        :setEntityCraftingCategories({db.forName("ore-crusher-category")})
        :setEntityCollisionBox({{-2.7, -2.7}, {2.7, 2.4}})  --左右 上下
        :setEntitySelectionBox({{-3.0, -2.7}, {3.0, 2.7}})
        :setEntityDrawingBox({{-3.2, -3.2}, {3.2, 3.2}})
        :setEntityAnimation({

            layers ={

                {
                    filename = db.forRes("OreCrusher/res/hr-genric-object-gen3-orecrusher.png"),
                    priority = "high",
--[[                    width = 978,
                    height = 895,]]
                    width = 350,
                    height = 315,
                    frame_count = 32,
                    line_length = 8,
                    shift = util.by_pixel(0, 0),
                    scale = 0.55,
                    hr_version =
                    {
                        filename = db.forRes("OreCrusher/res/hr-genric-object-gen3-orecrusher.png"),
                        priority = "high",
                        width = 350,
                        height = 315,
                        frame_count = 32,
                        line_length = 8,
                        shift = util.by_pixel(0, 0),
                        scale = 0.55
                    }
                },
                {
                    filename = db.forRes("OreCrusher/res/hr-genric-object-gen3-orecrusher-shadow.png"),
                    priority = "high",
                    width = 385,
                    height = 280,
                    frame_count = 32,
                    line_length = 8,
                    draw_as_shadow = true,
                    shift = util.by_pixel(20, -1),
                    scale = 0.5,
                    hr_version =
                    {
                        filename = db.forRes("OreCrusher/res/hr-genric-object-gen3-orecrusher-shadow.png"),
                        priority = "high",
                        width = 385,
                        height = 280,
                        frame_count = 32,
                        line_length = 8,
                        draw_as_shadow = true,
                        shift = util.by_pixel(20, -1),
                        scale = 0.5
                    }
                }

            }

        }):joinToData()