---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/26 2:03
---

aspectService.create(TypeEnum.item)
        :setName(db.forName("ore-crusher"))
        :setItemIcon(db.forRes("OreCrusher/res/hr-genric-object-gen3-orecrusher-icon.png"))
        :setItemIconSize(128)
        :setItemSubgroup(ItemSubgroupEnum.smeltingMachine)
        :setItemPlaceResult(db.forName("ore-crusher"))
        :setItemStackSize(10)
        :insertInto()