---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 10:52
---

--舰载冷却塔 - entity
local originCollingTower = data.raw["furnace"]["rr-cooling-tower"]
local marinePropulsionCoolingTower = nil

--舰载冷却塔水冷recipe
local marinePropulsionCoolingTowerWaterCollingRecipe = {
    type = "recipe",
    name = "marine-propulsion-water-cooling",
    category = "marine-propulsion-water-cooling",
    enabled = true,
    hidden = true,
    energy_required = 0.5,
    ingredients = {
        {type="fluid", name="water", amount=750},
    },
    results = {
        {type="fluid", name="water", amount=750},
    },
    icon = "__base__/graphics/icons/fluid/water.png",
    icon_size = 32,
    subgroup = "fluid-recipes",
    order = "z",
}

if originCollingTower~=nil then

    marinePropulsionCoolingTower = table.deepcopy(data.raw["furnace"]["rr-cooling-tower"])
    marinePropulsionCoolingTower.name = "kscp-cooling-tower"
    marinePropulsionCoolingTower.crafting_categories = {"marine-propulsion-water-cooling"}
    --[[marinePropulsionCoolingTower.collision_mask = {"object-layer", "train-layer", "floor-layer","water-tile","ground-tile","resource-layer"}]]
    marinePropulsionCoolingTower.collision_mask = {
        "water-tile",
        "ground-tile",
        "item-layer",
        "object-layer",
        "player-layer",
    }

    data:extend({marinePropulsionCoolingTower})
    data:extend({marinePropulsionCoolingTowerWaterCollingRecipe})
end


