---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 10:52
---

--舰载冷却塔
local originCollingTower = data.raw["item"]["rr-cooling-tower"]

local marinePropulsionCoolingTower = nil


if originCollingTower~=nil then

    marinePropulsionCoolingTower = table.deepcopy(data.raw["item"]["rr-cooling-tower"])
    marinePropulsionCoolingTower.name = "kscp-cooling-tower"
    marinePropulsionCoolingTower.place_result = "kscp-cooling-tower"

    data:extend({marinePropulsionCoolingTower})
end