---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/10 10:52
---
local originCollingTowerRecipe = data.raw["recipe"]["rr-cooling-tower"]
local marinePropulsionCoolingTowerRecipe = nil

if originCollingTowerRecipe~=nil then
    marinePropulsionCoolingTowerRecipe = table.deepcopy(data.raw["recipe"]["rr-cooling-tower"])
    marinePropulsionCoolingTowerRecipe.name = "kscp-cooling-tower"
    marinePropulsionCoolingTowerRecipe.result = "kscp-cooling-tower"
end

data:extend({marinePropulsionCoolingTowerRecipe})

