---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/7 15:50
---

local radar_amplification_type = 5

local max_distance_of_sector_revealed = data.raw['radar']['radar'].max_distance_of_sector_revealed + radar_amplification_type * 3
local max_distance_of_nearby_sector_revealed = data.raw['radar']['radar'].max_distance_of_nearby_sector_revealed + radar_amplification_type * 2

--[[local energy_per_sector = (10000 + extra_energy_cost * 40) / (1 + math.pow(radar_efficiency_type, 1.5))]]

local extra_energy_cost = 75 * radar_amplification_type


data.raw['radar']['radar'].max_distance_of_sector_revealed = 0

data.raw['radar']['radar'].max_distance_of_nearby_sector_revealed = 4
data.raw['radar']['radar'].energy_per_sector = 1 .. "kW"

data.raw['radar']['radar'].energy_usage = (300 + extra_energy_cost) .. "kW"