---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/26 16:55
---

local dataBuilderAnimation = {}

local insertLayerHolder = {
    filename = nil,
    priority = "high",
    width = nil,
    height = nil,
    frame_count = nil,
    line_length = nil,
    shift = nil,
    scale = nil,
    draw_as_shadow = false
}


function dataBuilderAnimation.create(width,height)
    insertLayerHolder.width = width
    insertLayerHolder.height = height
    dataBuilderAnimation.insertLayerHolder = insertLayerHolder
    return dataBuilderAnimation
end

function dataBuilderAnimation:setWidth(width)
    self.insertLayerHolder.width = width
end

function dataBuilderAnimation:setHeight(height)
    self.insertLayerHolder.height = height
end

function dataBuilderAnimation:setFrameCount(frameCount)
    self.insertLayerHolder.frame_count = frameCount
end

function dataBuilderAnimation:setLineLength(lineLength)
    self.insertLayerHolder.line_length = lineLength
end

function dataBuilderAnimation:setShift(shift)
    self.insertLayerHolder.shift = shift
end

function dataBuilderAnimation:setScale(scale)
    self.insertLayerHolder.scale = scale
end


return dataBuilderAnimation
