---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/4 10:03
---

--[[移除厂房合成]]

if data.raw["recipe"]["factory-1"]~=nil then
    data.raw["recipe"]["factory-1"] = nil
end

if data.raw["recipe"]["factory-2"]~=nil then
    data.raw["recipe"]["factory-1"] = nil
end

if data.raw["recipe"]["factory-3"]~=nil then
    data.raw["recipe"]["factory-1"] = nil
end



--[[移除厂房科技研究成果]]
if data.raw["technology"]["factory-architecture-t1"]~=nil then
    data.raw["technology"]["factory-architecture-t1"].effects = nil
end

if data.raw["technology"]["factory-architecture-t2"]~=nil then
    data.raw["technology"]["factory-architecture-t1"].effects = nil
end

if data.raw["technology"]["factory-architecture-t3"]~=nil then
    data.raw["technology"]["factory-architecture-t1"].effects = nil
end