---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/4 10:03
---

--[[移除厂房合成]]
data.raw["recipe"]["factory-1"] = nil
data.raw["recipe"]["factory-2"] = nil
data.raw["recipe"]["factory-3"] = nil


--[[移除厂房科技研究成果]]
data.raw["technology"]["factory-architecture-t1"].effects = nil
data.raw["technology"]["factory-architecture-t2"].effects = nil
data.raw["technology"]["factory-architecture-t3"].effects = nil
