---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 0:28
---



--[[
for name,fluid in pairs(aspectService.getList(TypeEnum.fluid)) do


    local recipe_fill = data.raw["recipe"]["fill-"..fluid.name.."-barrel"]
    local recipe_empty = data.raw["recipe"]["empty-"..fluid.name.."-barrel"]


    if recipe_fill~=nil and recipe_empty~=nil then

        data.raw["recipe"]["fill-"..fluid.name.."-barrel"].ingredients ={
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        }

        data.raw["recipe"]["empty-"..fluid.name.."-barrel"].results={
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        }

    end


end]]




for name,fluid in pairs(aspectService.getList(TypeEnum.fluid)) do



    local fill = aspectService.getRecipe("fill-"..fluid.name.."-barrel")


    if fill:isNotEmpty()then

        fill:setRecipeIngredients({
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        }):update()

    end

    local empty = aspectService.getRecipe("empty-"..fluid.name.."-barrel")


    if empty:isNotEmpty()then

        empty:setRecipeResults({
            {type = "fluid", name = fluid.name, amount = 50, catalyst_amount = 50}
        }):update()

    end









end
