---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 0:36
---

local suffix = "-barrel"

for name, fluid in pairs(aspectService.getList(TypeEnum.fluid)) do

    aspectService.getItem(fluid.name..suffix):setItemStackSize(75):insertToData()

end