---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 0:40
---

local itemStack = {
    {
        name="rocket-fuel",
        itemStack=75
    }

}



for i,itemName in pairs(itemStack) do

    aspectService.getItem(itemName.name):setItemStackSize(itemName.itemStack):insertToData()

end