---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/14 17:23
---
local aspectObject = require("aspect.AspectObject")

local aspectService = {}


function aspectService.get(type,name)

    --获取luaEntity
    local item = table.deepcopy(data.raw[type][name])

    --将luaEntity封装为AspectObject
    return aspectObject.create(item)
end


function aspectService.getItem(name)

    --获取luaEntity
    local item = table.deepcopy(data.raw["item"][name])

    --将luaEntity封装为AspectObject
    return aspectObject.create(item)

end


function aspectService.getRecipe(name)
    local recipe = table.deepcopy(data.raw["recipe"][name])
    return aspectObject.create(recipe)
end


function aspectService.getEntity(name)
    local entity = table.deepcopy(data.raw["entity"][name])
    return aspectObject.create(entity)
end


function aspectService.getTechnology(name)
    local technology = table.deepcopy(data.raw["technology"][name])
    return aspectObject.create(technology)
end

return aspectService


