---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/13 14:42
---

local entityService = {}

local operateTarget = "entity"


function entityService.removeEntity(entityName)

    local entity = data.raw[operateTarget][technologyName]

    if entity~=nil then
        data.raw[operateTarget][technologyName] = nil
    end

end

return entityService