---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/13 14:41
---
local itemService = {}
local operateTarget = "item"

function itemService.removeItem(itemName)

    local item = data.raw[operateTarget][itemName]

    if item~=nil then
        data.raw[operateTarget][itemName] = nil
    end

end

return itemService