---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/13 14:41
---

local recipeService = {}
local operateTarget = "recipe"


function recipeService.setResult(recipe,result)
    recipe.result = result
    return recipe
end

--移除合成表
function recipeService.removeRecipe(recipeName)

    local recipe = data.raw[operateTarget][recipeName]

    if recipe~=nil then
        data.raw[operateTarget][recipeName] = nil
    end

end

return recipeService
