---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/13 14:42
---
local technologyService = {}

local operateTarget = "technology"

function technologyService.removeTechnology(technologyName)

    local technology = data.raw[operateTarget][technologyName]

    if technology~=nil then
        data.raw[operateTarget][technologyName] = nil
    end

end


function technologyService.removeTechnologyEffects(technologyName)

    local technology = data.raw[operateTarget][technologyName]

    if technology~=nil then
        data.raw[operateTarget][technologyName].effects = nil
    end

end

return technologyService