---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/2/8 17:26
---




aspectConverter.toItem(aspectService.create(TypeEnum.item))
        :setName(db.forName("prism-structure-item"))
        :setIcon(db.forRes("PrismStructure/res/hr-prism-sturcture-item.png"))
        :setIconSize(128)
        :setStackSize(100)
        :setOrder("p[prism-structure-item]")
        :setSubgroup(ItemSubgroupEnum.intermediateProduct)
        :insertInto()













