---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/14 16:53
---

local aspectObject = {}

function aspectObject.create(luaObject)
    aspectObject.luaObject = luaObject
    return aspectObject;
end

function aspectObject.get(type,name)

    --获取luaEntity
    local item = table.deepcopy(data.raw[type][name])

    --将luaEntity封装为AspectObject
    return aspectObject.create(item)
end

function aspectObject:getSame(name)

    local luaEntity = self:getLuaObject()

    if luaEntity~=nil then

        --获取luaEntity
        local item = table.deepcopy(data.raw[luaEntity.type][name])

        --将luaEntity封装为AspectObject
        return aspectObject.create(item)
    end

    return aspectObject.create(nil)
end

function aspectObject:set(property,value)

    local luaEntity = self:getLuaObject()

    if luaEntity~=nil then
        luaEntity[property] = value
    end

    return self
end


function aspectObject:getLuaObject()
    return self.luaObject
end


function aspectObject:setLuaObject(luaObject)
    self.luaObject = luaObject
end

function aspectObject:getType()
    if self.luaObject~=nil then
        return self.luaObject.type
    end
end

function aspectObject:getName()
    if self.luaObject~=nil then
        return self.luaObject.name
    end
end

function aspectObject:setName(name)

    local luaEntity = self:getLuaObject()

    if luaEntity~=nil then
        luaEntity.name = name
    end

    return self
end


function aspectObject:removeFromData()

    local luaEntity = self:getLuaObject()

    if luaEntity~=nil then
        data.raw[luaEntity.type][luaEntity.name] = nil
    end

    return self
end

function aspectObject:insertToData()

    local luaEntity = self:getLuaObject()

    self:removeFromData()

    if luaEntity~=nil then
        data:extend({luaEntity})
    end

    return self
end

function aspectObject:joinToData()
    return self:insertToData()
end

function aspectObject:insertInto()
    return self:insertToData()
end


function aspectObject:update()

    local luaEntity = self:getLuaObject()


    if luaEntity~=nil then
        data.raw[luaEntity.type][luaEntity.name] = luaEntity
    end


    return self
end

function aspectObject:isNotEmpty()

    local luaEntity = self:getLuaObject()

    if luaEntity~=nil then
        return true
    end

    return false
end

function aspectObject:setRecipeIngredients(ingredients)
    return self:set("ingredients",ingredients)
end

function aspectObject:setRecipeResults(results)
    return self:set("results",results)
end

function aspectObject:setTechnologyEffects(effects)

    local luaEntity = self:getLuaObject()

    if luaEntity~=nil then
        luaEntity.effects = effects
    end

    return self
end

function aspectObject:getTechnologyEffects()


    local luaEntity = self:getLuaObject()

    if luaEntity~=nil then
        return luaEntity.effects
    end

    return nil
end

function aspectObject:setSolarPanelProduction(production)
    return self:set("production",production)
end

function aspectObject:setEntityMaxHealth(maxHealth)
    return self:set("max_health",maxHealth)
end


function aspectObject:setEntityEnergyUsage(energyUsage)
    return self:set("energy_usage",energyUsage)
end

function aspectObject:setEntityCraftSpeed(craftSpeed)
    return self:set("crafting_speed",craftSpeed)
end

function aspectObject:setEntityModuleSpecification(moduleSpecification)
    return self:set("module_specification",moduleSpecification)
end


function aspectObject:setEntityCollisionMask(collisionMask)
    return self:set("collision_mask",collisionMask)
end

function aspectObject:setAllowInSpace(allow)
    return self:set("se_allow_in_space",allow)
end

function aspectObject:setItemStackSize(stackSize)
    return self:set("stack_size",stackSize)
end

function aspectObject:setTechnologyPrerequisites(prerequisites)
    return self:set("prerequisites",prerequisites)
end

function aspectObject:setTechnologyUnit(unit)
    return self:set("unit",unit)
end




return aspectObject
