---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/7 15:48


local collision_mask =  {"object-layer", "train-layer", "floor-layer","water-tile"}


data.raw['furnace']['transport-belt-beltbox'].collision_mask = collision_mask
data.raw['furnace']['transport-belt-beltbox'].se_allow_in_space = true

data.raw['furnace']['fast-transport-belt-beltbox'].collision_mask = collision_mask
data.raw['furnace']['fast-transport-belt-beltbox'].se_allow_in_space = true

data.raw['furnace']['express-transport-belt-beltbox'].collision_mask = collision_mask
data.raw['furnace']['express-transport-belt-beltbox'].se_allow_in_space = true