---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/20 2:54
---


aspectService.getRecipe("underground-pipe-segment-space"):setRecipeIngredients({
    {"underground-pipe-segment-t1", 1},
    {"copper-cable", 2 },
    {ItemEnum.plasticBar, 1 },
    {"glass", 1 },

}):insertToData()

aspectService.getRecipe("space-pipe-coupler"):setRecipeIngredients({
    {'small-pipe-coupler', 1},
    {ItemEnum.copperCable, 2 },
    {ItemEnum.plasticBar, 1 },
}):insertToData()

aspectService.getTechnology("advanced-underground-piping-space")
        :setTechnologyPrerequisites({"advanced-underground-piping-t3"})
        :setTechnologyUnit({
            count = 200,
            ingredients = {
                {ToolEnum.automationSciencePack, 1},
                {ToolEnum.logisticSciencePack, 1},
                {ToolEnum.chemicalSciencePack, 1},
                {ToolEnum.utilitySciencePack, 1},
            },
            time = 30
        })
        :insertToData()


