---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/12 19:45
---

local surfaceManager = {}

--删除临时表面
function surfaceManager.removeTempSurface()

    local surfaceList = game.surfaces

    local isRemoveFactorySurface = settings.global["kscp-surface-manager-remove-factory-surface"].value

    for i,s in pairs(surfaceList) do

        if string.find(s.name,"starmap-") ~=nil then
            surfaceManager.removeSurface(s.name)
            game.print("移除图层:"..s.name)
        end

        if string.find(s.name,"Factory floor") ~=nil then
            if isRemoveFactorySurface == true then
                surfaceManager.removeSurface(s.name)
                game.print("移除图层:"..s.name)
            end
        end

    end

end

--删除表面
function surfaceManager.removeSurface(surfaceName)

    local wrSurface = game.get_surface(surfaceName)

    if wrSurface==nil then
        return
    end

    wrSurface.clear()
    game.delete_surface(wrSurface)
end

return surfaceManager;