---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/19 17:48
---
---
aspectService = require("modules.aspectcommonservices.AspectService")
constEnum = require("enums.ConstEnum")
typeEnum = require("enums.TypeEnum")
itemEnum = require("enums.ItemEnum")
toolEnum = require("enums.ToolEnum")


require("modules.SupportComponent.SpaceExploration.CoreMinerRemovers")