---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/19 17:48
---
---
aspectService = require("modules.aspectcommonservices.AspectService")
constEnum = require("enums.ConstEnum")
typeEnum = require("enums.TypeEnum")


require("modules.spaceexploration.CoreMinerRemovers")