---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/18 21:40
---

aspectService = require("modules.aspectcommonservices.AspectService")
constEnum = require("enums.ConstEnum")
typeEnum = require("enums.TypeEnum")
itemEnum = require("enums.ItemEnum")
toolEnum = require("enums.ToolEnum")



require("modules.SupportComponent.vanilla.BarrelRecipeUpgrader")
require("modules.SupportComponent.vanilla.BarrelStackSizeUpgrader")
require("modules.SupportComponent.vanilla.ItemStackSizeUpgrader")
require("modules.SupportComponent.vanilla.RaderUpgrader")
require("modules.SupportComponent.vanilla.RobotTowerUpgrader")



require("modules.SupportComponent.Warehouse.WarehousingUpgrader")


require("modules.SupportComponent.SpaceExploration.SpaceSolarPanelUpgrader")
require("modules.SupportComponent.SpaceExploration.DeliveryCannonCapsuleRecipeUpgrader")

require("modules.SupportComponent.MineDrone.MineDroneUpgrader")

require("modules.SupportComponent.UngroundPipePack.SpacePipeRecipeUpgrader")

require("modules.SupportComponent.DeadlockBeltboxesLoaders.DeadLockUpgrader")
