---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/19 17:46
---

aspectService = require("modules.AspectCommonService.AspectService")
require("enums.ConstEnum")
require("enums.TypeEnum")
require("enums.ItemEnum")
require("enums.ToolEnum")
require("enums.FluidEnum")
require("enums.RecipeCategoryEnum")
require("enums.SubgroupEnum")
require("enums.ExplosionEnum")
require("enums.TechnologyEnum")


---模块加载顺序
local modulesInitConfig = {
    "Entity","Item","Recipe","Technology"
}


---模块定义
local modulesDefine = {

    { name = "M1" , desc = "UU液体基础" ,  packName = db.forInnerModules("UUBase") },
    { name = "M2" , desc = "UU复制机" ,  packName = db.forInnerModules("UUDuplicator") },
    { name = "M3" , desc = "UU工厂" ,  packName = db.forInnerModules("UUMatterFabricator") },
    { name = "M4" , desc = "四号组装机" ,  packName = db.forInnerModules("AssemblingT4") },
    { name = "M5" , desc = "紧凑型反应堆" ,  packName = db.forInnerModules("CompactReactor") },
    { name = "M6" , desc = "光棱组件" ,  packName = db.forInnerModules("PrismStructure") }

}


---模块加载
local function loaderForModules(defines)

    for i,v in pairs(modulesDefine) do

        for i1,init in pairs(modulesInitConfig) do
            require(v.packName.."/"..init)
        end

    end

end


loaderForModules(modulesDefine)