---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/19 17:48
---
---
aspectService = require("modules.AspectCommonService.AspectService")
require("enums.ConstEnum")
require("enums.TypeEnum")
require("enums.ItemEnum")
require("enums.ToolEnum")
require("enums.FluidEnum")
require("enums.RecipeCategoryEnum")
require("enums.SubgroupEnum")
require("enums.ExplosionEnum")
require("enums.TechnologyEnum")

require("modules.SupportComponent.SpaceExploration.CoreMinerRemovers")