---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/25 17:11
---

aspectService.create(TypeEnum.recipeCategory,db.forName("uu-duplicator-category")):insertInto()


aspectService.create(TypeEnum.assemblingMachine)
        :setName(db.forName("uu-duplicator"))
        :setEntityCollisionMask(ConstEnum.collisionMaskAllowInGroundAndSpace)
        :setAllowInSpace(true)
        :setEntityMaxHealth(1500)
        :setEntityCraftSpeed(4)
        :setEntityModuleSpecification({
            module_slots = 4
        })
        :setEntityCraftingCategories({db.forName("uu-duplicator-category")})
        :setEntityCollisionBox({{-2.9, -2.9}, {2.9, 2.9}})
        :setEntitySelectionBox({{-3.2, -3.2}, {3.2, 3.2}})
        :setEntityDrawingBox({{-3, -3}, {3, 3}})

        :setEntityAnimation({

            layers ={

                {
                    filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-uu.png",
                    priority = "high",
                    width = 512,
                    height = 512,
                    frame_count = 32,
                    line_length = 8,
                    shift = util.by_pixel(0, 0),
                    scale = 0.52,
                    hr_version =
                    {
                        filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-uu.png",
                        priority = "high",
                        width = 512,
                        height = 512,
                        frame_count = 32,
                        line_length = 8,
                        shift = util.by_pixel(0, 0),
                        scale = 0.52
                    }
                },
                {
                    filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-gen1-shadow.png",
                    priority = "high",
                    width = 512,
                    height = 512,
                    frame_count = 32,
                    line_length = 8,
                    draw_as_shadow = true,
                    shift = util.by_pixel(0, 0),
                    scale = 0.52,
                    hr_version =
                    {
                        filename = ConstEnum.modulesPath.."UUMatterFabricator/res/hr-genric-object-gen1-shadow.png",
                        priority = "high",
                        width = 512,
                        height = 512,
                        frame_count = 32,
                        line_length = 8,
                        draw_as_shadow = true,
                        shift = util.by_pixel(0, 0),
                        scale = 0.52
                    }
                }

            }

        }):insertInto()

