---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/26 2:03
---

aspectService.create(TypeEnum.item)
        :setName(db.forName("uu-duplicator"))
        :setItemIcon(db.forRes("UUDuplicator/res/hr-genric-object-gen3-duplicator-icon.png"))
        :setItemIconSize(128)
        :setItemSubgroup(ItemSubgroupEnum.productionMachine)
        :setItemPlaceResult(db.forName("uu-duplicator"))
        :setItemStackSize(10)
        :insertInto()