---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/26 2:03
---


local aspect = aspectService.get(TypeEnum.technology,db.forName("uu-matter-fabricator"))

aspectConverter.toTechnology(aspect)