---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2021/12/28 10:52
---
-- 等待距离
data.raw.roboport.roboport.charge_approach_distance = 5 -- 默认 = 5

data.raw.roboport.roboport.collision_mask = {"object-layer", "train-layer", "floor-layer"}
data.raw.roboport.roboport.se_allow_in_space = true

-- 充电位置
data.raw.roboport.roboport.charging_offsets = {
    { -1.5, -1.5 },
    { -.75, -1.5 },
    {    0, -1.5 },
    {  .75, -1.5 },
    {  1.5, -1.5 },
    {  1.5, -.75 },
    {  1.5,  0   },
    {  1.5,  .75 },
--[[    {  1.5,  1.5 },
    {  .75,  1.5 },
    {    0,  1.5 },
    { -.75,  1.5 },
    { -1.5,  1.5 },
    { -1.5,  .75 },
    { -1.5,  0   },
    { -1.5, -.75 }]]
}

-- 每tick充电量
data.raw.roboport.roboport.charging_energy = "18MW" -- 默认 = 1000kW

-- 机器人能量接口
data.raw.roboport.roboport.energy_source = {
    type = "electric",
    usage_priority = "secondary-input",
    input_flow_limit = "75MW", -- 默认 = 5MW
    buffer_capacity = "500MJ" -- 默认 = 100MJ
}