---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/7 18:01
---

local collision_mask =  {"object-layer", "train-layer", "floor-layer","water-tile"}


data.raw['assembling-machine']['mining-depot'].collision_mask = collision_mask
data.raw['assembling-machine']['mining-depot'].se_allow_in_space = true