---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/10 23:15
---

local unmark = {};

function unmark.unmark_reactor(event)

    local player = event.player_index

    if not player then
        return
    end

    player = game.players[player]

    local entity = event.entity

    if entity.valid and entity.name == "kscp-compact-nuclear-reactor" then
        entity.cancel_deconstruction(player.force)
    end


end

return unmark


