---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/24 14:00
---

aspectService.get(TypeEnum.fluid,FluidEnum.water)
        :setName(db.forName("fluid-uu-matter"))
        :setItemIcon(ConstEnum.modulesPath.."UUBase/res/hr-fluid-uu.png")
        :setFluidHeatCapacity(nil)
        :setFluidGasTemperature(nil)
        :setFluidBaseColor({r=57,g=15,b=43})
        :setFluidFlowColor({r=0,g=162,b=232})
        :setFluidDefaultTemperature(-273)
        :setFluidMaxTemperature(-273)
        :insertInto()

        :getSame(FluidEnum.water)
        :setName(db.forName("fluid-uu-amplifier"))
        :setItemIcon(ConstEnum.modulesPath.."UUBase/res/hr-fluid-uu-amplifier.png")
        :setFluidHeatCapacity(nil)
        :setFluidGasTemperature(nil)
        :setFluidBaseColor({r=27,g=0,b=45})
        :setFluidFlowColor({r=122,g=184,b=208})
        :setFluidDefaultTemperature(-273)
        :setFluidMaxTemperature(-273)
        :insertInto()

aspectService.create(TypeEnum.item,db.forName("uu-matter"))
        :setItemStackSize(150)
        :setItemIcon(ConstEnum.modulesPath.."UUBase/res/hr-uu-matter.png")
        :setItemIconSize(32)
        :setItemSubgroup("raw-resource")
        :setItemOrder("u[uu-matter]")
        :insertInto()

aspectService.create(TypeEnum.item,db.forName("uu-amplifier"))
             :setItemStackSize(100)
             :setItemIcon(ConstEnum.modulesPath.."UUBase/res/hr-uu-amplifier.png")
             :setItemIconSize(64)
             :setItemSubgroup("raw-resource")
             :setItemOrder("u[uu-amplifier]")
             :insertInto()

