---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KspTooi.
--- DateTime: 2022/1/24 14:00
---


local ingredients = db.buildIngredients(TypeEnum.item,db.forName("uu-matter"),1)

local rst = {
    {
        type = TypeEnum.fluid,
        name = db.forName("fluid-uu-matter"),
        amount = 10
    }

}


crafting_machine_tint = { primary = {r=57,g=15,b=43}, secondary = {r=57,g=15,b=43}, tertiary = {r=57,g=15,b=43}, quaternary = {r=57,g=15,b=43}}



local object = aspectService.create(TypeEnum.recipe)

aspectConverter.toRecipe(object)

        :setName(db.forName("uu-matter-to-fluid"))
        :setIcon(db.forRes("UUBase/res/hr-fluid-uu-recipe.png"))
        :setIconSize(64)
        :setIngredients(ingredients:build())
        :setResult(rst)
        :setCategory(RecipeCategoryEnum.chemistry)
        :setSubgroup(ItemSubgroupEnum.fluidRecipes)
        :setCraftingMachineTint(crafting_machine_tint)
        :setEnergyRequired(0.6)
        :insertInto()
